### ISSUE TITLE
Tests tests tests

### ISSUE THREAD

**Issue by peermaute** [peermaute/MealSquare#21]

**Comment by calfaand** [comment]
Hello, can I contribute to this project with writing tests ?

**Comment by peermaute** [comment]
> Hello, can I contribute to this project with writing tests ?

Hey @calfaand ,
In theory sure, you're welcome!
But most tests that are needed are for the Controller.class. To test that, you'd need access tokens for standard users and for  an admin user. I could implement methods with environment variables, but actually that is most of the work for this project and writing the tests afterwards is a matter of minutes.
So you might rather search for a different project to contribute some testing.

Have a good day,
Peer

**Comment by peermaute** [comment]
Change MealService Tests to be dynamic for fetchByProperties

**Comment by peermaute** [comment]
Rewrite tests for Controller.class with authentication/authorization
